package main.java;

/**
 * The sequence of triangle numbers is generated by adding the natural numbers.
 * So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28.
 * The first ten terms would be:  * 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
 * What is the value of the first triangle number to have over five hundred divisors?
 */
public class Problem_12 {
    public static void main(String[] args) {
        long number = 1L;
        long nextNatural = 1L;
        long count = 0L;

        while (count < 500) {
            int i = 1;
            count = 0;
            while (i <= number) {
                if (number % i == 0) {
                    count++;
                }
                i++;
            }
            System.out.println(number + " has " + count + " divisors.");
            nextNatural++;
            number += nextNatural;
        }
        System.out.println(number - nextNatural);
    }
}
